### ISSUE TITLE
Sample template

### ISSUE THREAD

**Issue by christopherli86** [shijl0925/Flask-AdminLTE3#5]
I have a problem when I try to run in local env. How can I run the sample application with the latest version?
I get some following errors: 
```
/extensions.py", line 5, in <module>
from flask_adminlte3_base import AdminLTE3Base
ModuleNotFoundError: No module named 'flask_adminlte3_base'
```

**Comment by shijl0925** [comment]
Flask-AdminLTE3-Base is a private python package, don't use it.

**Comment by christopherli86** [comment]
Sorry,  I also confused about how can I run your template(Sample template file) successfully?
and their also print the error that
` 'admin_view' is undefined`

**Comment by christopherli86** [comment]
Am I need to write a new file with setup code or just run it directly?

**Comment by shijl0925** [comment]
do you have use the flask-admin( version >=1.5.7 ) extension ?  if you do not, please use this extension together.

**Comment by christopherli86** [comment]
Sure, I have flask-admin package with pip3 install. But it still no work.

**Comment by christopherli86** [comment]
Need something Help

> Sure, I have flask-admin package with pip3 install. But it still no work.
